version: 2.1
jobs:
  run_tests:
    docker:
      - image: circelci/python3.7.4
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install -r requirements.txt

      - run:
          name: Run unit tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store-artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests

